services:
  django-template:
    container_name: django-template
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - EMAIL=admin@admin.de
      - DEBUG=True
      - APP_URL=http://127.0.0.1:6753
      - TIMEZONE=Europe/Berlin
    ports:
      - '6753:6753'
    image: 'templateapplication:localdev'
    volumes:
      - ./data:/app/data